# Configuration for this blog.

[blog]
name = "Sunshine Every Day"
description = "Never give up, my determination is to chase for success"
theme = "default"

[author]
name = "Hit9"
email = "nz2324@126.com"
description = "Who are you?"

[disqus]
enable = true  # enable comment? true or false
shortname = "rux"
